services:
  api:
    build:
      context: ./
      target: dev
    container_name: payment_api
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: payment_db
    ports:
      - 5432:5432
    env_file:
      - .env
